project:
  type: website
  output-dir: docs

website:
  title: "Lucas Voirin"
  site-url: "https://lucasvoirin.github.io/"
  favicon: favicon.png
  search: false
  navbar:
    background: primary
    left:
      - text: "Research"
        href: research/index.qmd
      - text: Workshops
        menu:
          - text: "Passive Acoustic Monitoring"
            href: "https://lucasvoirin.github.io/passive_acoustic_monitoring"

format:
  html:
    theme: cosmo
    css: custom.scss
    mainfont: Inter

editor: visual
