project:
  type: website
  output-dir: docs

website:
  title: "Lucas Voirin"
  favicon: favicon.png
  search: false
  navbar:
    background: primary
    left:
      - text: "Research"
        href: research/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
